"""prints a pip --require-hashes lock file for the distribution files in the given directory"""

import hashlib
import os
import sys

from packaging.utils import parse_sdist_filename, parse_wheel_filename

directory = sys.argv[1]
print("# generated by appimage/build.sh --relock, do not edit")
for fname in sorted(os.listdir(directory), key=str.lower):
    if fname.endswith('.whl'):
        name, version, _, _ = parse_wheel_filename(fname)
    else:
        name, version = parse_sdist_filename(fname)
    with open(os.path.join(directory, fname), 'rb') as f:
        digest = hashlib.sha256(f.read()).hexdigest()
    print("%s==%s \\\n    --hash=sha256:%s" % (name, version, digest))
